version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in a Docker volume
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    image: blog_tech_django
    environment:
      - DB_HOST=postgres
      - DB_NAME=testdb
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_PORT=5432
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:  # Define the volume for the PostgreSQL service
